---
image:
  name: ansible:2.7-1

stages:
  # test: testinfraの実行
  - test


services:
  - name: basenode:1.0
    alias: server
    command: [ "/sbin/init" ]

before_script:
  - mkdir ~/.ssh
  - cp /home/ansible/.ssh/id_rsa ~/.ssh/id_rsa

test_result:
  stage: test
  script:
    - ansible-playbook -i tests/inventory tests/test.yml --skip--tags packages
    - py.test --hosts=ansible@server tests/test_mariadb.py
