---
image:
  name: ansible:2.7-1

stages:
  - lint
  - test


services:
  - name: basenode:1.0
    alias: server
    command: [ "/sbin/init" ]

before_script:
  - mkdir ~/.ssh
  - cp /home/ansible/.ssh/id_rsa ~/.ssh/id_rsa
  - pip install pexpect


check_syntax:
  stage: lint
  script:
    - ansible-playbook -i tests/inventory tests/test.yml --check


test_result:
  stage: test
  script:
    - ansible-playbook -i tests/inventory tests/test.yml --skip-tags upgrade
    - py.test --hosts=ansible@server tests/test_mariadb.py
