---
image:
  name: ansible:2.7-1

stages:
  - lint
  - test


services:
  #- name: basenode:1.0
  - name: ospctrlr:1.0
    alias: controller
    command: [ "/sbin/init" ]

before_script:
  - mkdir ~/.ssh
  - cp /home/ansible/.ssh/id_rsa ~/.ssh/id_rsa

check_syntax:
  stage: lint
  script:
    - ansible-playbook -i tests/inventory tests/test.yml --check

test_result:
  stage: test
  script:
    - ansible-playbook -i tests/inventory tests/test.yml --skip-tags packages,mariadb,queue,memcached,etcd -vvv
    - py.test --hosts=ansible@server tests/test_mariadb.py
    - py.test --hosts=ansible@server tests/test_rabbitmq.py
    - py.test --hosts=ansible@server tests/test_memcached.py
    - py.test --hosts=ansible@server tests/test_etcd.py
