
- include_tasks: init_database.yml
  vars:
    database_name: glance
    database_user: glance
    database_pass: "{{ minimal_openstack_glance_dbpass }}"

- include_tasks: init_service.yml
  vars:
    service_name: glance
    service_type: image
    service_user_name: glance
    service_user_pass: "{{ minimal_openstack_glance_user_password }}"
    service_description: "Openstack Image"

- name: Create image endpoint
  include_tasks: endpoint.yml
  vars:
    service: "image"
    interface: "{{ item }}"
    url: "http://controller:9292"
  with_items:
    - "public"
    - "internal"
    - "admin"

- name: install openstack-glance
  yum: 
    name: openstack-glance
    state: present

- name: update glance configuration
  ini_file:
    path: /etc/glance/glance-api.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    # Database
    - { section: database, 
        option: connection,
        value: "mysql+pymysql://glance:{{ minimal_openstack_glance_dbpass }}@controller/glance" }
    # Keystone authtoken
    - { section: keystone_authtoken,
        option: www_authenticate_uri,
        value: http://controller:5000}
    - { section: keystone_authtoken,
        option: auth_url,
        value: http://controller:5000}
    - { section: keystone_authtoken,
        option: memcached_servers,
        value: controller:11211 }
    - { section: keystone_authtoken,
        option: auth_type,
        value: password }
    - { section: keystone_authtoken,
        option: project_domain_name,
        value: Default}
    - { section: keystone_authtoken,
        option: user_domain_name,
        value: Default}
    - { section: keystone_authtoken,
        option: project_name,
        value: service}
    - { section: keystone_authtoken,
        option: username,
        value: glance}
    - { section: keystone_authtoken,
        option: password,
        value: "{{ minimal_openstack_glance_user_password }}"}
    - { section: paste_deploy,
        option: flavor,
        value: keystone}
    # glance store
    - { section: glance_store,
        option: stores,
        value: "file,http"}
    - { section: glance_store,
        option: default_store,
        value: file}
    - { section: glance_store,
        option: filesystem_store_datadir,
        value: "/var/lib/glance/images/" }

- name: populate glance service
  shell: "su -s /bin/sh -c 'glance-manage db_sync' glance"

- name: start glance-api
  service:
    name: openstack-glance-api.service
    enabled: yes
    state: restarted


