
- name: check database existence
  command: "{{ sql }} -e 'use {{ database_name }};'"
  failed_when: false
  register: ret

- name: create databases
  block:
    - command: "{{ sql }} -e 'CREATE DATABASE {{ database_name }};'"
    - command: >
          {{ sql }} -e \
            "GRANT ALL PRIVILEGES ON {{ database_name }}.*  \
             TO '{{ database_user }}'@'localhost'  \
             IDENTIFIED BY '{{ database_pass }}';"

    - command: >
        {{ sql }} -e  \
          "GRANT ALL PRIVILEGES ON {{ database_name }}.*  \
           TO '{{ database_user }}'@'%'  \
           IDENTIFIED BY '{{ database_pass }}';"

  when: ret.rc != 0