---

- set_fact:
    openstack: >
      openstack 
      --os-interface public 
      --os-project-name admin 
      --os-user-domain-name default 
      --os-project-domain-name default
      --os-username admin
      --os-auth-url http://controller:5000/v3 
      --os-password {{ minimal_openstack_admin_password }}
      --os-auth-type v3password

- set_fact:
    sql: "mysql -u root -p{{ minimal_openstack_mariadb_password }}"

- include_tasks: packages.yml
  tags: packages
- include_tasks: mariadb.yml
  tags: mariadb
- include_tasks: queue.yml
  tags: queue
- include_tasks: memcached.yml
  tags: memcached
- include_tasks: etcd.yml
  tags: etcd

- include_tasks: keystone.yml
  tags: keystone

- include_tasks: glance.yml
  tags: glance

- include_tasks: placement.yml
  tags: placement

- include_tasks: nova.yml
  tags: nova

- include_tasks: neutron.yml
  tags: neutron

- include_tasks: heat.yml
  tags: heat
