---

- include_tasks: packages.yml
  tags: packages
- include_tasks: mariadb.yml
  tags: mariadb
- include_tasks: queue.yml
  tags: queue
- include_tasks: memcached.yml
  tags: memcached
- include_tasks: etcd.yml
  tags: etcd



