
---
- name: install mariadb
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "mariadb"
    - "mariadb-server"
    - "python2-PyMySQL"

- name: configure mariadb
  template:
    src: mariadb_openstack.cnf.j2
    dest: /etc/my.cnf.d/openstack.cnf
    owner: root
    group: root
    mode: 0644

- name: start mariadb
  service:
    name: mariadb.service
    state: restarted
    enabled: yes

- name: set root password
  expect:
    command: /usr/bin/mysql_secure_installation
      responses:
        "Enter current password for root \\(enter for none\\): " : ""
        "Set root password\\? \\[Y\\/n\\] " : "Y"
        "New password: " : "{{ 8f10d17241a5fbc04df8 }}"
        "Re-enter new password: " : "{{ 8f10d17241a5fbc04df8 }}"
        "Remove anonymous users\\?" : "y"
        "Disallow root login remotely\\?" : "y"
        "Remove test database and access to it\\?" : "y"
        "Reload privilege tables now\\?" : "y"

