
- name: install memcached
  yum: 
    name: memcached
    state: present

- name: configure memcached
  lineinfile:
    path: /etc/sysconfig/memcached
    line: 'OPTIONS="-l 127.0.0.1,::1,controller"'
    regexp: '^OPTIONS='

- name: start memcached
  service:
    name: memcached.service
    state: restarted
    enabled: yes

