
- name: install neutron agent packages
  yum:
    name:
      - openstack-neutron-linuxbridge
      - ebtables 
      - ipset
    state: present

- name: configure nova.conf for neutron
  ini_file:
    path: /etc/nova/nova.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { 
      section: neutron,
      option: auth_url,
      value: http://controller:5000
    }
    - { 
      section: neutron,
      option: auth_type,
      value: password
    }
    - { 
      section: neutron,
      option: project_domain_name,
      value: default
    }
    - { 
      section: neutron,
      option: user_domain_name,
      value: default
    }
    - { 
      section: neutron,
      option: region_name,
      value: RegionOne
    }
    - { 
      section: neutron,
      option: project_name,
      value: service
    }
    - { 
      section: neutron,
      option: username,
      value: neutron
    }
    - { 
      section: neutron,
      option: password,
      value: "{{ minimal_openstack_neutron_user_password }}"
    }

- name: enable neutron-linuxbridge-agent.service
  service:
    name: neutron-linuxbridge-agent.service
    enabled: yes
    state: restarted
