
- name: install neutron packages
  yum:
    name: 
      - openstack-neutron
      - openstack-neutron-ml2 
      - openstack-neutron-linuxbridge 
      - ebtables

- name: configure neutron.conf
  ini_file:
    path: /etc/neutron/neutron.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { 
      section: database,
      option: connection,
      value: "mysql+pymysql://neutron:{{ minimal_openstack_neutron_dbpass }}@controller/neutron"
    }
    - { 
      section: DEFAULT,
      option: core_plugin,
      value: ml2
    }
    - { 
      section: DEFAULT,
      option: service_plugins,
      value: router
    }
    - { 
      section: DEFAULT,
      option: allow_overlapping_ips,
      value: "true"
    }
    - { 
      section: DEFAULT,
      option: transport_url,
      value: "rabbit://openstack:{{ minimal_openstack_rabbitmq_password }}@controller"
    }
    - { 
      section: DEFAULT,
      option: auth_strategy,
      value: "keystone"
    }
    - { 
      section: keystone_authtoken,
      option: www_authenticate_uri,
      value: http://controller:5000
    }
    - { 
      section: keystone_authtoken,
      option: auth_url,
      value: http://controller:5000
    }
    - { 
      section: keystone_authtoken,
      option: memcached_servers,
      value: controller:11211
    }
    - { 
      section: keystone_authtoken,
      option: auth_type,
      value: password
    }
    - { 
      section: keystone_authtoken,
      option: project_domain_name,
      value: default
    }
    - { 
      section: keystone_authtoken,
      option: user_domain_name,
      value: default
    }
    - { 
      section: keystone_authtoken,
      option: project_name,
      value: service
    }
    - { 
      section: keystone_authtoken,
      option: username,
      value: neutron
    }
    - { 
      section: keystone_authtoken,
      option: password,
      value: "{{ minimal_openstack_neutron_user_password }}"
    }

    # to notify compute
    - {
      section: DEFAULT,
      option: notify_nova_on_port_status_changes,
      value: "true"
    }
    - {
      section: DEFAULT,
      option: notify_nova_on_port_data_changes,
      value: "true"
    }
    - {
      section: nova,
      option: auth_url,
      value: http://controller:5000
    }
    - {
      section: nova,
      option: auth_type,
      value: password
    }
    - {
      section: nova,
      option: project_domain_name,
      value: default
    }
    - {
      section: nova,
      option: user_domain_name,
      value: default
    }
    - {
      section: nova,
      option: region_name,
      value: RegionOne
    }
    - {
      section: nova,
      option: project_name,
      value: service
    }
    - {
      section: nova,
      option: username,
      value: nova
    }
    - {
      section: nova,
      option: password,
      value: "{{ minimal_openstack_nova_user_password }}"
    }
    - {
      section: oslo_concurrency,
      option: lock_path,
      value: "/var/lib/neutron/tmp"
    }

- name: configure ml2_conf.ini
  ini_file:
    path: /etc/neutron/plugins/ml2/ml2_conf.ini
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { 
      section: ml2,
      option: type_drivers,
      value: "flat,vlan,vxlan"
    }
    - { 
      section: ml2,
      option: tenant_network_types,
      value: vxlan
    }
    - { 
      section: ml2,
      option: mechanism_drivers,
      value: "linuxbridge,l2population"
    }
    - { 
      section: ml2,
      option: extension_drivers,
      value: port_security
    }
    - { 
      section: ml2_type_flat,
      option: flat_networks,
      value: provider
    }
    - { 
      section: ml2_type_vxlan,
      option: vni_ranges,
      value: "1:1000"
    }
    - { 
      section: securitygroup,
      option: enable_ipset,
      value: "true"
    }

- name: configure linuxbridge_agent.ini
  ini_file:
    path: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { 
      section: linux_bridge,
      option: physical_interface_mappings,
      value: "{{ minimal_openstack_controller_provider_physical_network_interface }}"
    }
    - { 
      section: vxlan,
      option: enable_vxlan,
      value: "true"
    }
    - { 
      section: vxlan,
      option: local_ip,
      value:  "{{ minimal_openstack_controller_management_ip }}"
    }
    - { 
      section: vxlan,
      option: l2_population,
      value:  "true"
    }
    - { 
      section: securitygroup,
      option: enable_security_group,
      value:  "true"
    }
    - { 
      section: securitygroup,
      option: firewall_driver,
      value:  neutron.agent.linux.iptables_firewall.IptablesFirewallDriver
    }

- name: load br_netfilter
  copy:
    src: br_netfilter.modules
    dest: /etc/sysconfig/modules/br_netfilter.modules
    owner: root
    group: root
    mode: 0755

- command: modprobe br_netfilter

- name: enable bridge-nf-call-iptables
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1

- name: enable bridge-nf-call-ip6tables
  sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: 1

- name: configure l3_agent.ini
  ini_file:
    path: /etc/neutron/l3_agent.ini
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { 
      section: DEFAULT,
      option: interface_driver,
      value: "linuxbridge"
    }

- name: configure dhcp_agent.ini
  ini_file:
    path: /etc/neutron/dhcp_agent.ini
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { 
      section: DEFAULT,
      option: interface_driver,
      value: "linuxbridge"
    }
    - { 
      section: DEFAULT,
      option: dhcp_driver,
      value: neutron.agent.linux.dhcp.Dnsmasq
    }
    - { 
      section: DEFAULT,
      option: enable_isolated_metadata,
      value: "true"
    }


