---

- name: setup repository
  yum:
    name: centos-release-openstack-train
    state: present

- name: upgrade all packages
  yum:
    name: '*'
    state: latest
  tags: upgrade

- name: install required packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "python-openstackclient"
    - "openstack-selinux"

